name: Swift

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test
        env:
          BRANTA_SKIP_INTEGRATION: "1"
